name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Pack Iterum.Core
      run: dotnet pack Iterum.Core/Iterm.Core.csproj --configuration Release
    - name: Pack Iterum.Math
      run: dotnet pack Iterum.Math/Iterum.Math.csproj --configuration Release
    - name: Pack Iterum.PhysX
      run: dotnet pack Iterum.PhysX/Iterm.PhysX.csproj --configuration Release
    - name: Pack Iterum.ThingTypes
      run: dotnet pack Iterum.ThingTypes/Iterm.ThingTypes.csproj --configuration Release
    - name: Pack Iterum.ThingTypes
      run: dotnet pack Iterum.WebSockets/Iterm.WebSockets.csproj --configuration Release
    - name: Push all
      run: dotnet nuget push **/*.nupkg --source "github" --skip-duplicate
