name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Pack Iterum.Math
      run: |
        dotnet pack Iterum.Math/Iterum.Math.csproj --configuration Release
        dotnet nuget push Iterum.Math/**/*.nupkg --source "github" --skip-duplicate
    - name: Pack Iterum.Core
      run: |
        dotnet pack Iterum.Core/Iterum.Core.csproj --configuration Release
        dotnet nuget push Iterum.Core/**/*.nupkg --source "github" --skip-duplicate
    - name: Pack Iterum.PhysX
      run: |
        dotnet pack Iterum.PhysX/Iterum.PhysX.csproj --configuration Release
        dotnet nuget push Iterum.PhysX/**/*.nupkg --source "github" --skip-duplicate
    - name: Pack Iterum.ThingTypes
      run: |
        dotnet pack Iterum.ThingTypes/Iterum.ThingTypes.csproj --configuration Release
        dotnet nuget push Iterum.ThingTypes/**/*.nupkg --source "github" --skip-duplicate